# This is a basic workflow to help you get started with Actions

name: Run bot

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      #- "main.py"
      - "modules.py"
  schedule:
    - cron: "1 */5 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip packages
        run: |
          pip install setuptools
          pip install pip --upgrade
          echo `python3 --version`

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      # Runs the bot
      - name: Configure the runner
        run: |
          echo "${{ secrets.CONFIG_FILE_CONTENT }}" > config.py 
          python3 main.py
